Update SRE posting for new reqs
rcbops/rackspace_privatecloud_jobs pull request #11
Opened 2018-02-28 17:17 UTC by CrashenX

2018-02-28 17:20 UTC, jedsmith requested changes
Xing for a typo, just general questions for the rest.

2018-02-28 17:20 UTC, jedsmith commented on sre-operational-fabric.md
> +- Help drive the architecture, develop, and maintain configuration maangement of customer environments
`maangement` -> `management`

2018-02-28 17:20 UTC, jedsmith commented on sre-operational-fabric.md
> +- Help drive the architecture, develop, and maintain configuration maangement of customer environments
Should we add a bullet back for observability? Not sure about losing that concept.

2018-02-28 17:20 UTC, jedsmith commented on sre-operational-fabric.md
> +- Experience instituting configuration management (e.g. Ansible Tower)
", Puppet, Chef" will get more leads

2018-02-28 17:21 UTC, CrashenX commented on sre-operational-fabric.md
> +- Experience instituting configuration management (e.g. Ansible Tower)
kk

2018-02-28 18:22 UTC, jedsmith approved these changes

2018-02-28 18:22 UTC, jedsmith commented
Thanks!

2018-02-28 18:38 UTC, merged

2018-03-12 02:10 UTC, neillc commented
Coluld you please remove from this org.  I haven't worked for Rackspace for over a year and have requested removal multiple times.